"""add field type to news_kanal

Revision ID: 00535ed14918
Revises: 222c0a2ed62a
Create Date: 2018-06-09 22:14:48.666424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00535ed14918'
down_revision = '222c0a2ed62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_kanal', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_kanal', 'type')
    # ### end Alembic commands ###
