"""initial DB

Revision ID: 222c0a2ed62a
Revises: 
Create Date: 2018-06-07 09:51:02.723551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222c0a2ed62a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_kanal',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_portal', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_post',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_portal', sa.Integer(), nullable=True),
    sa.Column('link_news', sa.Text(), nullable=True),
    sa.Column('kanal_index', sa.Text(), nullable=True),
    sa.Column('scrap_status', sa.Boolean(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('category_sub', sa.Text(), nullable=True),
    sa.Column('date_publish', sa.DateTime(), nullable=True),
    sa.Column('image_link', sa.Text(), nullable=True),
    sa.Column('image_link_alt', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('editor', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keyword', sa.Text(), nullable=True),
    sa.Column('meta_content_category', sa.Text(), nullable=True),
    sa.Column('meta_content_category_sub', sa.Text(), nullable=True),
    sa.Column('meta_content_location', sa.Text(), nullable=True),
    sa.Column('meta_content_author', sa.Text(), nullable=True),
    sa.Column('meta_content_editor', sa.Text(), nullable=True),
    sa.Column('meta_content_lipsus', sa.Text(), nullable=True),
    sa.Column('meta_content_type', sa.Text(), nullable=True),
    sa.Column('meta_content_publish_date', sa.DateTime(), nullable=True),
    sa.Column('meta_content_source', sa.Text(), nullable=True),
    sa.Column('meta_content_tag', sa.Text(), nullable=True),
    sa.Column('meta_content_total_words', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portal',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('home_page', sa.String(), nullable=True),
    sa.Column('link_index', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portal')
    op.drop_table('news_post')
    op.drop_table('news_kanal')
    # ### end Alembic commands ###
